# Generated by Django 3.1 on 2020-08-27 10:38

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200826_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=ecommerce.models.user_directory_path, verbose_name='Image'),
        ),
    ]
